### ISSUE TITLE
Add  Commitlint  to husky

### ISSUE THREAD

**Issue by tmohammad78** [mohsenshafiei/zyme#8]
### Clear and concise description of the problem

Commit message is important, we should have some rules for it.

### Suggested solution

add [Commitlint](https://github.com/conventional-changelog/commitlint) to pre commit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/mohsenshafiei/zyme/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/mohsenshafiei/zyme/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](NA).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mohsenshafiei** [comment]
closed #8
